---
- name: Configure Cisco Router with SSH
  hosts: routers
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Set hostname
      cisco.ios.ios_config:
        lines:
          - hostname Router1

    - name: Configure enable secret
      cisco.ios.ios_config:
        lines:
          - enable secret StrongPassword123

    - name: Configure MOTD banner
      cisco.ios.ios_config:
        lines:
          - banner motd #Unauthorized access is prohibited!#

    - name: Configure GigabitEthernet0/0 with IP and enable it
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.1.1 255.255.255.0
          - no shutdown
        parents: interface GigabitEthernet0/0

    - name: Configure standard ACL 10
      cisco.ios.ios_config:
        lines:
          - access-list 10 permit 192.168.1.0 0.0.0.255

    - name: Apply ACL inbound on GigabitEthernet0/0
      cisco.ios.ios_config:
        lines:
          - ip access-group 10 in
        parents: interface GigabitEthernet0/0

    - name: Configure default route to ISP
      cisco.ios.ios_config:
        lines:
          - ip route 0.0.0.0 0.0.0.0 203.0.113.1

    - name: Set domain name (required for SSH)
      cisco.ios.ios_config:
        lines:
          - ip domain-name example.local

    - name: Generate RSA keys for SSH
      cisco.ios.ios_command:
        commands:
          - crypto key generate rsa modulus 2048

    - name: Create local user for SSH login
      cisco.ios.ios_config:
        lines:
          - username admin privilege 15 secret AdminPass123

    - name: Configure VTY lines for SSH only
      cisco.ios.ios_config:
        lines:
          - login local
          - transport input ssh
        parents: line vty 0 4

    - name: Save configuration
      cisco.ios.ios_config:
        save_when: always
