---
- name: Configure Cisco Switch
  hosts: switches
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Set hostname
      cisco.ios.ios_config:
        lines:
          - hostname Switch1

    - name: Configure enable secret
      cisco.ios.ios_config:
        lines:
          - enable secret StrongPassword123

    - name: Configure MOTD banner
      cisco.ios.ios_config:
        lines:
          - banner motd #Unauthorized access is prohibited!#

    - name: Create VLANs
      cisco.ios.ios_config:
        lines:
          - vlan 10
          - name Sales
          - vlan 20
          - name HR
          - vlan 30
          - name IT

    - name: Configure management VLAN IP
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.1.2 255.255.255.0
          - no shutdown
        parents: interface vlan 1

    - name: Configure default gateway
      cisco.ios.ios_config:
        lines:
          - ip default-gateway 192.168.1.1

    - name: Assign VLAN 10 to Fa0/1
      cisco.ios.ios_config:
        lines:
          - switchport mode access
          - switchport access vlan 10
        parents: interface FastEthernet0/1

    - name: Assign VLAN 20 to Fa0/2
      cisco.ios.ios_config:
        lines:
          - switchport mode access
          - switchport access vlan 20
        parents: interface FastEthernet0/2

    - name: Assign VLAN 30 to Fa0/3
      cisco.ios.ios_config:
        lines:
          - switchport mode access
          - switchport access vlan 30
        parents: interface FastEthernet0/3

    - name: Configure console line
      cisco.ios.ios_config:
        lines:
          - password ciscocon
          - login
          - logging synchronous
        parents: line console 0

    - name: Configure VTY lines
      cisco.ios.ios_config:
        lines:
          - password ciscovty
          - login
          - transport input telnet ssh
        parents: line vty 0 4

    - name: Shutdown unused ports (Fa0/4 - Fa0/24)
      cisco.ios.ios_config:
        lines:
          - shutdown
        parents: interface range FastEthernet0/4 - 24

    - name: Save configuration
      cisco.ios.ios_config:
        save_when: always
